---
- hosts: all
  become: yes
  roles:
    - { role: install-docker, tags: ["install_docker_role"] }

- hosts: manager
  become: yes
  roles:
    - { role: setup-swarm-manager, tags: ["setup_swarm_manager_role"] }

- hosts: managernodes
  become: yes
  roles:
    - { role: add-secundary-manager, tags: ["add_secundary_manager_role"] }

- hosts: worker
  become: yes
  roles:
    - { role: add-worker, tags: ["add_worker_role"] }   

- hosts: manager
  become: yes
  roles:
    - { role: deploy-stack, tags: ["deploy_stack_role"] }